const BASE_URL = import.meta.env.VITE_URL_BACK;
//rutas
export const RUTA_BACK_PRODUCCION = BASE_URL;
//login
export const INICIAR_SESION = "INICIAR_SESION";
export const OBTENER_TOKEN = "OBTENER_TOKEN";
//logout
export const CERRAR_SESION = "CERRAR_SESION";
//sidebar
export const OCULTAR_BARRA_LATERAL = "OCULTAR_BARRA_LATERAL";
export const MOSTRAR_BARRA_LATERAL = "MOSTRAR_BARRA_LATERAL";
//innoProduc
export const INNPRODUC_OBTENER = "INNPRODUC_OBTENER";
export const INNPRODUC_NO_DATA= "INNPRODUC_NO_DATA";
//regchangepass
export const REGCHANGEPASS_INFO_USUARIO = "REGCHANGEPASS_INFO_USUARIO";
export const REGCHANGEPASS_TIME_EXPIRED = "REGCHANGEPASS_TIME_EXPIRED";
//Areas de servicio
export const AREAS_SERVICIO_OBTENER = "AREAS_SERVICIO_OBTENER";
//mesa de procesos
export const MESAPROCESOS_USUARIOS_POR_AREA_OBTENER = "USUARIOS_MESAPROCESOS_POR_AREA_OBTENER";
export const MESAPROCESOS_AGREGAR_USUARIO_A_AREA = "MESAPROCESOS_AGREGAR_USUARIO_A_AREA";
export const MESAPROCESOS_AGREGAR_PROCESO_A_AREA = "MESAPROCESOS_AGREGAR_PROCESO_A_AREA";
export const MESAPROCESOS_ACTUALIZAR_PROCESO_DE_AREA = "MESAPROCESOS_ACTUALIZAR_PROCESO_DE_AREA";
export const MESAPROCESOS_AGREGAR_SUBPROCESO_A_PROCESO = "MESAPROCESOS_AGREGAR_SUBPROCESO_A_PROCESO";
export const MESAPROCESOS_ELIMINAR_USUARIO_DE_AREA = "MESAPROCESOS_ELIMINAR_USUARIO_DE_AREA";
export const MESAPROCESOS_ACTUALIZAR_USUARIO_DE_AREA = "MESAPROCESOS_ACTUALIZAR_USUARIO_DE_AREA";
export const MESAPROCESOS_ACTUALIZAR_SUBPROCESOS_DE_PROCESO = "MESAPROCESOS_ACTUALIZAR_SUBPROCESOS_DE_PROCESO";